version: "3.8"

services:
  # 开发环境
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm-store
    ports:
      - "7566:3000"
    environment:
      - NODE_ENV=development

volumes:
  # 持久化 node_modules
  node_modules:
    name: app-node-modules

  # 持久化 pnpm 存储
  pnpm_store:
    name: app-pnpm-store
